// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA03rB53iQWErPE0DbxsOQ55oa3ihyc344',
    appId: '1:1013005310795:web:f1e07c226937e1f5d4e6ce',
    messagingSenderId: '1013005310795',
    projectId: 'newattnd',
    authDomain: 'newattnd.firebaseapp.com',
    storageBucket: 'newattnd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqU0Jd_qKrJRrB-Q1YvjPqNxuxESJOXG0',
    appId: '1:1013005310795:android:89be690f97854cc2d4e6ce',
    messagingSenderId: '1013005310795',
    projectId: 'newattnd',
    storageBucket: 'newattnd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsvlhvk-VR65zS_OXBT9WnxcF-HZS6HOI',
    appId: '1:1013005310795:ios:bfe1327eda9ccdaad4e6ce',
    messagingSenderId: '1013005310795',
    projectId: 'newattnd',
    storageBucket: 'newattnd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsvlhvk-VR65zS_OXBT9WnxcF-HZS6HOI',
    appId: '1:1013005310795:ios:bfe1327eda9ccdaad4e6ce',
    messagingSenderId: '1013005310795',
    projectId: 'newattnd',
    storageBucket: 'newattnd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA03rB53iQWErPE0DbxsOQ55oa3ihyc344',
    appId: '1:1013005310795:web:ed07263fa0dd1db4d4e6ce',
    messagingSenderId: '1013005310795',
    projectId: 'newattnd',
    authDomain: 'newattnd.firebaseapp.com',
    storageBucket: 'newattnd.appspot.com',
  );
}
